# -*- coding: utf-8 -*-
"""Test_123.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQJiLc2qWsueaLYp_oigD-YVxUegknXJ
"""

print("Hello")